### PR TITLE
Added a pause button to Game Page.

### LINKED ISSUE #31: Add a Pause button to the joypad
Add a `Pause` or `Options` button to the Joypad to pause the game and show the pause menu of the game.

### PR DESCRIPTION
**Pull request by ritvij14**
## Related Issues:
Fixes #31 

## Description:
I have made a simple Pause button widget that can be used to pause the games and show pause-menu for that game.

### CODE REVIEW

**Comment by janvig** [comment]
Hey @ritvij14, I don't see the pause button in play mode, it's there in the edit mode though.

**Comment by ritvij14** [comment]
@janvig sorry about that, I messed up while merging these commits with the recent PR that got merged. I have added the pause button to GamePage(), please have a look now.

**Review by janvig — COMMENTED** [review]
The updated position of the pause button is saved in the edit mode but not reflected in the play mode, can you check that once?

**Comment by ritvij14** [comment]
@janvig I have updated the changes. Now everything should be working correctly.

**Review by janvig — APPROVED** [review]
Works fine :+1:

**Comment by sanket143** [comment]
give @ritvij14 75 points

**Pull request merged**
