### PR TITLE
Storing data in local storage from the beginning

### PR DESCRIPTION
**Pull request by ritvij14**

### CODE REVIEW

**Review by janvig — CHANGES_REQUESTED** [review]
Set default coordinates only on `firstOpen`, else every time you reopen you get back to the defaults.

**Comment by ritvij14** [comment]
> Set default coordinates only on `firstOpen`, else every time you reopen you get back to the defaults.

Done, now I am calling a function to set initial coordinates only when the username is being saved while first time of opening the app.

**Comment by janvig** [comment]
nit: Adding an if statement and calling `initialiseCoordinates()` in `init()` of [Storage_service.dart](https://github.com/sinix-dev/sinix-mobile/blob/master/lib/services/Storage_service.dart) seems better to me thinking of us providing _Edit Username_ at some point in future, and that's when I think you'll again need to shift the call to `initialiseCoordinates()` back to `init()` because as per the current logic you'll reset the coordinates on username update as well.

**Comment by ritvij14** [comment]
@janvig changed it 👍

**Review by janvig — APPROVED** [review]

**Pull request merged**
