### PR TITLE
Gyroscope Value event added.

### PR DESCRIPTION
**Pull request by ritvij14**

### CODE REVIEW

**Comment by sanket143** [comment]
Could this be a widget so that it could fit in [here](https://github.com/sinix-dev/sinix-mobile/tree/furnishing/lib/pages/controller)

**Comment by ritvij14** [comment]
> Could this be a widget so that it could fit in [here](https://github.com/sinix-dev/sinix-mobile/tree/furnishing/lib/pages/controller)

What kind of widget would it be tho? As it's just event listeners, we will have to think of some widget in the design and then implement this in that.

**Comment by sanket143** [comment]
It could be an empty stateless widget with this exact logic so that controller can send sensor values only if that widget is present.

**Comment by ritvij14** [comment]
@sanket143 done, please have a look

**Pull request merged**
